In [ ]:
 exercicio - Estastistica descritiva (medida de tendencias central )

Um pesquisador ficou em determinado cruzamento durante 18 dias. Nesse cruzamento movimentado em media o nivel  de ruido (em decibes)


Media

In [ ]:
# carga o dataset 
# calcular a medida 
# df. campo.mean()

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("datasets/dataset_ruido.csv")

In [5]:
df.head()

   numero do dia  nivel ruido (dB)
0              1                85
1              2                92
2              3                95
3              4                98
4              5                99

In [6]:
df.tail()

    numero do dia  nivel ruido (dB)
13             14               120
14             15               120
15             16               122
16             17               125
17             18               127

In [7]:
df.tail()

    numero do dia  nivel ruido (dB)
13             14               120
14             15               120
15             16               122
16             17               125
17             18               127

In [9]:
df['nivel ruido (dB)'].mean()

np.float64(108.44444444444444)